#! /usr/bin/env python

Import( 'env' )
print("-------- Scons for jack_backend----------")
env = env.Clone()
env.MergeFlags( "-I# -I#/libcore -I#/backend   " )
env.MergeFlags( "-lsndfile" )
env.StaticLibrary( target="jackmix_backend", source=["jack_backend.cpp"] )

