#! /usr/bin/env python

Import( 'env' )
print("-------- Scons for libelements----------")
env = env.Clone()

env.AppendUnique( CPPPATH = ["#/libmatrix","#/libgui","#/libcore","#/libcontrol", "#/backend"] )
#env.StaticLibrary( target="jackmix_mixingelements", source=["stereo_elements.cpp","aux_elements.cpp"] )

#add my own element
env.StaticLibrary( target="jackmix_mixingelements", source=["stereo_elements.cpp","aux_elements.cpp","unity_elements.cpp"] )
