#! /usr/bin/env python

Import( 'env' )
print("-------- Scons for libqlash----------")
env = env.Clone()

env.MergeFlags( env['LASH10_FLAGS'] )
env.StaticLibrary( target="qlash", source= ['qlash.cpp'] )

